### PR TITLE
Use glmnet_jll instead of BinaryProvider

### PR DESCRIPTION
**Pull request by JackDunnNZ**

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
Bump, @ararslan would appreciate if you could take a look

**Comment by ararslan** [comment]
And now they're gone

**Comment by JackDunnNZ** [comment]
Thanks so much! Would you be able to tag a release?

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/10255

**Pull request merged**
