### PR TITLE
Add support to multinomial and Cox models

### PR DESCRIPTION
**Pull request by linxihui**
Here are the main changes:
1. Add file Multinomial.jl:  multi-class calssification
2. Add file CoxNet.jl: Cox model for survival data
3. Allow `y` to be string vector for logistic and multinomial classification
4. Add to `predict`: key word argument `outtype` for `link` and `probability` outcome; `predict` for `GLMNetCrossValidation` using the best `lambda`
5. Add plotting for elastic-net path, cross validation object
6. Add `coef`, `lambdamin` for `GLMNetCrossValidation` type
7. Add a classification example to README
8. Add tests

### CODE REVIEW

**Comment by linxihui** [comment]
Hi Simon,

Seems that there are still some problems in my branch, but do you know what "Coverage decreased" means?

Thanks,
Eric

**Comment by simonster** [comment]
Thanks for working on this! "Coveraged decreased" means that there is new code that isn't covered by the tests. It would be great to have something in `test/runtests.jl` to make sure that the Cox and multinomial models give the same results as e.g. R glmnet.

**Comment by linxihui** [comment]
More functionality added, test passed and code coverage are not bad now.  Can you merge and create a new tag?  Thanks!

**Comment by maximsch2** [comment]
Is there something that is holding up this PR?

**Comment by simonster** [comment]
Just me. I'll take a closer look in the next couple days.

**Comment by slundberg** [comment]
This might need merged before the sparse data support...

**Comment by jeffwong** [comment]
Would love to see cox support merged

**Comment by linxihui** [comment]
@simonster  Is there still people watching and maintaining this package? I feel that things are so lagging behind.

**Comment by ararslan** [comment]
I don't think this package is actively maintained right now. For Cox proportional hazards models, see https://github.com/ararslan/Survival.jl.

**Comment by Marco-Congedo** [comment]
This is a nice package. Will someone taking it over and pushing it forward?

**Comment by JackDunnNZ** [comment]
Revived and merged in #50

**Pull request closed without merging**
