### PR TITLE
Added support for sparse data matrices.

### PR DESCRIPTION
**Pull request by slundberg**
Needed when fitting to large sparse data sets. Addresses #9

### CODE REVIEW

**Comment by slundberg** [comment]
The problems with travis seem to be an unrelated 0.6 issue. Any chance we can merge this? ...it is a pain keeping my own copy of GLMNet in sync since I need to use sparse data.

**Comment by jeffwong** [comment]
Would love to have this functionality too. @slundberg I looked at the travis-ci log and saw this

```
while loading /home/travis/.julia/v0.6/GLMNet/test/runtests.jl, in expression starting on line 143
ERROR: LoadError: MethodError: convert(::Type{Array{Float64,2}}, ::GLMNet.CompressedPredictorMatrix) is ambiguous. Candidates:
  convert(::Type{T}, X::GLMNet.CompressedPredictorMatrix) where T<:Array{Float64,2} in GLMNet at /home/travis/.julia/v0.6/GLMNet/src/GLMNet.jl:80
  convert(::Type{Array{T,n}}, x::AbstractArray{S,n}) where {T, n, S} in Base at array.jl:328
Possible fix, define
  convert(::Type{Array{Float64,2}}, ::GLMNet.CompressedPredictorMatrix)
```

Does this mean anything to you?

**Comment by jeffwong** [comment]
I'm still new to Julia and don't know what happened between v 0.5 and v 0.6, though through some digging I believe the issue is in this test:

https://github.com/simonster/GLMNet.jl/blob/master/test/runtests.jl#L121

At this point path.betas is a GLMNet.CompressedPredictorMatrix. I think the fix for travis might be a one line change here

https://github.com/simonster/GLMNet.jl/blob/master/src/GLMNet.jl#L79

Does the function signature just need to change from 

```
X::CompressedPredictorMatrix
```
to
```
X::GLMNet.CompressedPredictorMatrix
```

**Comment by slundberg** [comment]
Hey! It does seem like a 0.6 change. Things are busy here for me right now
(just had a kid) so I won't be able to look into it but I think you are on
the right track.

**Comment by jeffwong** [comment]
Congratulations! Maybe @simonster can help me to verify the issue and then it can get merged?

**Comment by jeffwong** [comment]
bump. @simonster would you be able to take a look? Thanks!

**Comment by ararslan** [comment]
I'm going to close and reopen this so that (hopefully) the Travis status hook will update to point to JuliaStats instead of Simon's account. That will make it a bit easier to look at the failures in depth.

**Comment by ararslan** [comment]
The issue causing the failure has been fixed. This PR now just needs some syntactic updates for deprecated syntax and it should be good to go. I can push some commits to this branch soon to fix it up if you're still busy, @slundberg.

**Comment by ararslan** [comment]
Continued in #25 with Scott's authorship preserved.

**Pull request closed without merging**
